return {
  { "junegunn/goyo.vim" },
  { "sheerun/vim-polyglot" },
  { "morhetz/gruvbox" },
  { "preservim/nerdtree" },
  { "Xuyuanp/nerdtree-git-plugin" },
  { "neoclide/coc.nvim" },
  { "vim-latex/vim-latex" },
  { "vim-pandoc/vim-pandoc" },
  { "vim-pandoc/vim-pandoc-syntax" },
  { "chrisbra/Colorizer" },
  { "gabrielelana/vim-markdown" },
  { "scrooloose/nerdcommenter" },
  { "ryanoasis/vim-devicons" },
  { "tpope/vim-surround" },
  { "vim-airline/vim-airline-themes" },
  { "voldikss/vim-floaterm" },
  { "terryma/vim-smooth-scroll" },
  { "nvim-treesitter/nvim-treesitter", branch = 'master', lazy = false, build = ":TSUpdate"},
  { "nvim-lua/plenary.nvim" },
  { "easymotion/vim-easymotion" },
  { "junegunn/rainbow_parentheses.vim" },
  { "vim-autoformat/vim-autoformat" },
  { "nvim-telescope/telescope.nvim", tag = "0.1.8" },
  { "inkarkat/vim-ReplaceWithRegister" },
  { "williamboman/mason.nvim" },
  { "neovim/nvim-lspconfig" },
}
